from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
import io

app = Flask(__name__)
CORS(app)

# ── Home route ─────────────────────────────────────────
@app.route('/')
def home():
    return jsonify({"message": "GramaDharini API is running!"})

# ── Internships API ────────────────────────────────────
@app.route('/api/internships', methods=['GET'])
def get_internships():
    internships = [
        {"id": 1, "title": "Web Developer Intern",      "company": "TechStartup India", "location": "Remote",             "duration": "2 Months", "stipend": "₹5,000/month", "category": "Technology"},
        {"id": 2, "title": "Data Entry Intern",          "company": "NGO Connect",       "location": "Pune, Maharashtra",  "duration": "3 Months", "stipend": "Stipend provided","category": "NGO"},
        {"id": 3, "title": "Content Writer Intern",      "company": "EduMedia",          "location": "Remote",             "duration": "1 Month",  "stipend": "₹3,000/month", "category": "Writing"},
        {"id": 4, "title": "Agriculture Research Intern","company": "KrishiTech",        "location": "Nashik, Maharashtra","duration": "2 Months", "stipend": "₹4,000/month", "category": "Agriculture"},
        {"id": 5, "title": "Graphic Design Intern",      "company": "CreativeHub",       "location": "Remote",             "duration": "2 Months", "stipend": "₹6,000/month", "category": "Design"},
        {"id": 6, "title": "Social Media Intern",        "company": "BharatBrand",       "location": "Remote",             "duration": "1 Month",  "stipend": "₹2,500/month", "category": "Marketing"},
    ]
    return jsonify(internships)

# ── Resume PDF Generator ───────────────────────────────
@app.route('/api/resume', methods=['POST'])
def generate_resume():
    data = request.json

    name       = data.get('name', 'Student Name')
    email      = data.get('email', '')
    phone      = data.get('phone', '')
    location   = data.get('location', '')
    about      = data.get('about', '')
    education  = data.get('education', '')
    skills     = data.get('skills', '')
    experience = data.get('experience', '')
    languages  = data.get('languages', '')

    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Header background
    c.setFillColor(colors.HexColor("#1D9E75"))
    c.rect(0, height - 120, width, 120, fill=True, stroke=False)

    # Name
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(40, height - 55, name)

    # Contact
    c.setFont("Helvetica", 11)
    contact = f"{email}  |  {phone}  |  {location}"
    c.drawString(40, height - 80, contact)

    # GramaDharini tag
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(40, height - 100, "Generated by GramaDharini – ग्रामधारिणी")

    # Helper function for sections
    y = height - 145

    def draw_section(title, content):
        nonlocal y
        if not content:
            return
        if y < 80:
            c.showPage()
            y = height - 40

        # Section title
        c.setFillColor(colors.HexColor("#1D9E75"))
        c.setFont("Helvetica-Bold", 12)
        c.drawString(40, y, title.upper())
        y -= 6

        # Underline
        c.setStrokeColor(colors.HexColor("#1D9E75"))
        c.line(40, y, width - 40, y)
        y -= 16

        # Content
        c.setFillColor(colors.HexColor("#333333"))
        c.setFont("Helvetica", 10)

        # Word wrap
        words = content.split()
        line = ""
        for word in words:
            test = line + word + " "
            if c.stringWidth(test, "Helvetica", 10) < width - 80:
                line = test
            else:
                c.drawString(40, y, line.strip())
                y -= 15
                line = word + " "
                if y < 80:
                    c.showPage()
                    y = height - 40
        if line:
            c.drawString(40, y, line.strip())
            y -= 15
        y -= 10

    draw_section("About Me", about)
    draw_section("Education", education)
    draw_section("Skills", skills)
    draw_section("Experience / Projects", experience)
    draw_section("Languages Known", languages)

    c.save()
    buffer.seek(0)

    return send_file(
        buffer,
        mimetype='application/pdf',
        as_attachment=True,
        download_name=f"{name.replace(' ', '_')}_Resume.pdf"
    )

if __name__ == '__main__':
    app.run(debug=True, port=5000)